!include ../std.justfile
!include desktop.just

packages:
    pkg upgrade -y
    pkg install -y $(cat packages | xargs)

ssh:
    # Make sure to use -p 8022 when connecting to this! (then just add your key and use it as you want to.)
    pkg install -y dropbear
    passwd

yt-dlp:
    python -m pip install -U yt-dlp
