!include ../std.justfile

packages:
    pkg upgrade -y
    pkg install -y $(cat packages | xargs)

ssh:
    # Make sure to use -p 8022 when connecting to this! (then just add your key and use it as you want to.)
    pkg install -y dropbear
    passwd

yt-dlp:
    python -m pip install -U yt-dlp

vnc:
    pkg install -y x11-repo
    pkg install -y tigervnc

xfce:
    pkg install xfce4
    echo -e "#!/data/data/com.termux/files/usr/bin/sh\nxfce4-session &" | tee $HOME/.vnc/xstartup

setup-vnc:
    vncserver -localhost
    killall -9 vncserver
